---
- name: Install and configure a LAMP stack 
  hosts: all
  become: yes
  vars:
    apache_pkg: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    mysql_pkg: "{{ 'mysql-server' if ansible_os_family == 'Debian' else 'mariadb-server' }}"
    php_pkg: "{{ ['php', 'libapache2-mod-php', 'php-mysql'] if ansible_os_family == 'Debian' else ['php', 'php-mysql'] }}"

  tasks:
    - name: Update the package cache for Debian/Ubuntu
      package:
        name: '*'
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Install Apache, MySQL/MariaDB, and PHP
      package:
        name: "{{ [apache_pkg, mysql_pkg] + php_pkg }}"
        state: present

    - name: Start and enable Apache
      service:
        name: "{{ apache_pkg }}"
        state: started
        enabled: true

    - name: Start and enable MySQL/MariaDB
      service:
        name: "{{ mysql_pkg }}"
        state: started
        enabled: true

    - name: Create a test PHP page
      copy:
        dest: /var/www/html/info.php
        content: |
          <?php phpinfo(); ?>
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: "{{ apache_pkg }}"
        state: restarted
