name: Deploy Playbooks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Run any Ansible playbook using your local container action
      - name: Run Any Ansible Playbook
        uses: ./ 
        with:
          inventory: "ansible/hosts"
          playbook: "ansible-projects/lampsetup_pb.yml"
          extra_vars: "env=dev"
          become: "true"
          verbosity: "2"

