name: Deploy Playbooks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Any Ansible Playbook
        uses: ./  # local action
        with:
          inventory: "ansible/hosts"
          playbook: "ansible-projects/lampsetup_pb.yml"
          extra_vars: "env=dev"
          become: "true"
          verbosity: "2"
